### PR TITLE
Add Flickr api function

### PR DESCRIPTION
**Pull request by takfukuda917**
add Flickr api function

screencapture-localhost-8000-view-album-1487466354202

### CODE REVIEW

**Comment by danactive** [comment]
@takfukuda917 Tip on how-to [edit a commit message in SourceTree Windows (already pushed to remote)](http://stackoverflow.com/questions/17604232/edit-a-commit-message-in-sourcetree-windows-already-pushed-to-remote#23239109)

**Comment by takfukuda917** [comment]
@danactive Please check the pull request #124

**Comment by danactive** [comment]
@takfukuda917 I cloned your branch and I'm not seeing any Flickr gallery. Please provide steps on how to view your feature you are delivering
screen shot 2017-02-28 at 21 01 35

**Comment by danactive** [comment]
@takfukuda917

**Comment by danactive** [comment]
@takfukuda917 Oops closed the PR too soon.

I found where the JavaScript is failing
screen shot 2017-02-28 at 21 08 27

**Comment by danactive** [comment]
@takfukuda917 Further investigation the AJAX call has invalid geocode
https://api.flickr.com/services/rest?method=flickr.photos.search&api_key=671aab1520e2cb69e08dd36a5f40213b&has_geo=1&lat=undefined&lon=undefined&radius=1&radius_units=km&extras=geo

**Comment by takfukuda917** [comment]
@danactive Fixed bug! Please check

**Pull request closed without merging**
